-- Create the subscribers table
create table public.subscribers (
  id bigint generated by default as identity primary key,
  email text not null unique,
  channel text,
  marketing_consent boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table public.subscribers enable row level security;

-- Create a policy that allows inserting data via the API (Anon key)
create policy "Enable insert for everyone" on public.subscribers
  for insert with check (true);

-- (Optional) Create a policy that allows reading only your own data, or strictly limit select
-- For a newsletter, usually public read is NOT allowed.
